### ISSUE TITLE
Multiple images posts problems

### ISSUE THREAD

**Issue by fabmazz** [ZeeRooo/MaterialFBook#204]
**Description** : when there are posts with multiple pictures, clicking/touching a pictures opens the picture full screen. But when there are many pictures, the site shows a "+3" overlay that, when clicked should point to the complete list of pictures.
In the app, clicking on the overlay "+3" actually opens the last image showed, and the rest of the pictures cannot be seen.
Thank you for the work, I hope that the app keeps improving

**Comment by ZeeRooo** [comment]
Fixed on v3.8.7: https://github.com/ZeeRooo/MaterialFBook/releases/tag/v3.8.7

Tell me if it's fixed for you, so i can close the issue.

**Comment by fabmazz** [comment]
I'm sorry but the problem isn't fixed yet with the new version.

Il giorno Gio 3 Gen 2019, 00:16 Juan <notifications@github.com> ha scritto:

**Comment by fabmazz** [comment]
I was trying with a public post, and it didn't work. I will try with a friend's post later to see if it is working.
Thanks for the work!

**Comment by fabmazz** [comment]
It is fixed in the latest version!! Thank you for the work
