### ISSUE TITLE
Black text on black background with MaterialAmoled web theme

### ISSUE THREAD

**Issue by hackel** [ZeeRooo/MaterialFBook#83]
When using the MaterialAmoled web theme, I cannot see what I'm writing when trying to post a status update or share a link.  I have to highlight the text to read it.  Hopefully this is just a minor CSS change.  It would be great if you could support custom themes / CSS files somehow.

I'm using the latest version, 3.3.0.

**Comment by Lokdal** [comment]
I have this problem too!

**Comment by ZeeRooo** [comment]
Fixed on v3.4. Sorry for the inconvenient.

https://github.com/ZeeRooo/MaterialFBook/raw/master/apks/MaterialFBook_3.4.0.apk

**Comment by hackel** [comment]
I just upgraded to 3.4.1 and am still experiencing this issue, unfortunately.
